{{- if .Values.config.externalSecrets.enabled }}
apiVersion: {{ .Values.config.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "application-base.fullname" . }}
  labels:
    {{- include "application-base.labels" . | nindent 4 }}
    {{- with .Values.config.externalSecrets.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $annotations := merge (.Values.config.externalSecrets.annotations | default dict) (.Values.commonAnnotations | default dict) }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.config.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.config.externalSecrets.secretStoreRef.name | quote }}
    kind: {{ .Values.config.externalSecrets.secretStoreRef.kind | quote }}
  target:
    name: {{ default (include "application-base.fullname" .) .Values.config.externalSecrets.target.name | quote }}
    creationPolicy: {{ .Values.config.externalSecrets.target.creationPolicy | quote }}
    deletionPolicy: {{ .Values.config.externalSecrets.target.deletionPolicy | quote }}
    {{- with .Values.config.externalSecrets.target.template }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with .Values.config.externalSecrets.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.config.externalSecrets.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

