{{- if and .Values.workload.enabled (eq .Values.workload.type "stateless") }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "application-base.fullname" . }}
  labels:
    {{- include "application-base.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.workload.autoscaling.enabled }}
  replicas: {{ .Values.workload.replicas }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.workload.stateless.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "application-base.selectorLabels" . | nindent 6 }}
  strategy:
    {{- if eq .Values.workload.stateless.strategy.type "rollingUpdate" }}
    canary:
      maxSurge: {{ .Values.workload.stateless.strategy.rollingUpdate.maxSurge | quote }}
      maxUnavailable: {{ .Values.workload.stateless.strategy.rollingUpdate.maxUnavailable | quote }}
    {{- else if eq .Values.workload.stateless.strategy.type "canary" }}
    canary:
      {{- with .Values.workload.stateless.strategy.canary.stableService }}
      stableService: {{ . | quote }}
      {{- end }}
      {{- with .Values.workload.stateless.strategy.canary.canaryService }}
      canaryService: {{ . | quote }}
      {{- end }}
      {{- with .Values.workload.stateless.strategy.canary.trafficRouting }}
      trafficRouting:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- with .Values.workload.stateless.strategy.canary.steps }}
      steps:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- if .Values.workload.stateless.strategy.canary.analysis.enabled }}
      analysis:
        {{- with .Values.workload.stateless.strategy.canary.analysis.templates }}
        templates:
          {{- toYaml . | trimSuffix "\n" | nindent 10 }}
        {{- end }}
        {{- with .Values.workload.stateless.strategy.canary.analysis.args }}
        args:
          {{- toYaml . | trimSuffix "\n" | nindent 10 }}
        {{- end }}
        {{- if ne .Values.workload.stateless.strategy.canary.analysis.startingStep nil }}
        startingStep: {{ .Values.workload.stateless.strategy.canary.analysis.startingStep }}
        {{- end }}
      {{- end }}
    {{- else if eq .Values.workload.stateless.strategy.type "blueGreen" }}
    blueGreen:
      activeService: {{ default (include "application-base.fullname" .) .Values.workload.stateless.strategy.blueGreen.activeService | quote }}
      {{- with .Values.workload.stateless.strategy.blueGreen.previewService }}
      previewService: {{ . | quote }}
      {{- end }}
      autoPromotionEnabled: {{ .Values.workload.stateless.strategy.blueGreen.autoPromotionEnabled }}
      scaleDownDelaySeconds: {{ .Values.workload.stateless.strategy.blueGreen.scaleDownDelaySeconds }}
      {{- if .Values.workload.stateless.strategy.blueGreen.prePromotionAnalysis.enabled }}
      prePromotionAnalysis:
        {{- with .Values.workload.stateless.strategy.blueGreen.prePromotionAnalysis.templates }}
        templates:
          {{- toYaml . | trimSuffix "\n" | nindent 10 }}
        {{- end }}
        {{- with .Values.workload.stateless.strategy.blueGreen.prePromotionAnalysis.args }}
        args:
          {{- toYaml . | trimSuffix "\n" | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.workload.stateless.strategy.blueGreen.postPromotionAnalysis.enabled }}
      postPromotionAnalysis:
        {{- with .Values.workload.stateless.strategy.blueGreen.postPromotionAnalysis.templates }}
        templates:
          {{- toYaml . | trimSuffix "\n" | nindent 10 }}
        {{- end }}
        {{- with .Values.workload.stateless.strategy.blueGreen.postPromotionAnalysis.args }}
        args:
          {{- toYaml . | trimSuffix "\n" | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "application-base.selectorLabels" . | nindent 8 }}
        {{- with .Values.workload.podLabels }}
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
        {{- end }}
      {{- $annotations := merge (.Values.workload.podAnnotations | default dict) (.Values.commonAnnotations | default dict) }}
      {{- with $annotations }}
      annotations:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "application-base.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.accessControl.serviceAccount.automountServiceAccountToken }}
      {{- with .Values.workload.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- with .Values.workload.podSecurityContext }}
      securityContext:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- with .Values.workload.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- if .Values.workload.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.workload.terminationGracePeriodSeconds }}
      {{- end }}
      {{- with .Values.workload.initContainers }}
      initContainers:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "application-base.name" . }}
          image: {{ include "application-base.image" . | quote }}
          imagePullPolicy: {{ .Values.workload.image.pullPolicy }}
          {{- with .Values.workload.command }}
          command:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.args }}
          args:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.ports }}
          ports:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with include "application-base.containerEnvBlock" . }}{{- . | nindent 10 }}{{- end }}
          {{- with include "application-base.containerEnvFromBlock" . }}{{- . | nindent 10 }}{{- end }}
          {{- with .Values.workload.resources }}
          resources:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.securityContext }}
          securityContext:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.readinessProbe }}
          readinessProbe:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.livenessProbe }}
          livenessProbe:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.startupProbe }}
          startupProbe:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.lifecycle }}
          lifecycle:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with include "application-base.containerVolumeMountsBlock" . }}{{- . | nindent 10 }}{{- end }}
        {{- with .Values.workload.extraContainers }}
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
        {{- end }}
      {{- with include "application-base.podVolumesBlock" . }}{{- . | nindent 6 }}{{- end }}
      {{- with .Values.workload.nodeSelector }}
      nodeSelector:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- with .Values.workload.affinity }}
      affinity:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- with .Values.workload.tolerations }}
      tolerations:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- with .Values.workload.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
{{- end }}
