{{- if .Values.network.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-base.fullname" . }}
  labels:
    {{- include "application-base.labels" . | nindent 4 }}
    {{- with .Values.network.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $annotations := merge (.Values.network.service.annotations | default dict) (.Values.commonAnnotations | default dict) }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.network.service.type }}
  sessionAffinity: {{ .Values.network.service.sessionAffinity }}
  selector:
    {{- include "application-base.selectorLabels" . | nindent 4 }}
  ports:
    {{- toYaml .Values.network.service.ports | nindent 4 }}
{{- end }}
{{- if .Values.network.headlessService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-base.fullname" . }}-headless
  labels:
    {{- include "application-base.labels" . | nindent 4 }}
    {{- with .Values.network.headlessService.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $annotations := merge (.Values.network.headlessService.annotations | default dict) (.Values.commonAnnotations | default dict) }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  selector:
    {{- include "application-base.selectorLabels" . | nindent 4 }}
  ports:
    {{- if .Values.network.headlessService.ports }}
    {{- toYaml .Values.network.headlessService.ports | nindent 4 }}
    {{- else }}
    {{- toYaml .Values.network.service.ports | nindent 4 }}
    {{- end }}
{{- end }}

