{{- if and .Values.workload.enabled (eq .Values.workload.type "stateful") }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "application-base.fullname" . }}
  labels:
    {{- include "application-base.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.workload.autoscaling.enabled }}
  replicas: {{ .Values.workload.replicas }}
  {{- end }}
  serviceName: {{ ternary (printf "%s-headless" (include "application-base.fullname" .)) (include "application-base.fullname" .) .Values.network.headlessService.enabled }}
  podManagementPolicy: {{ .Values.workload.stateful.podManagementPolicy }}
  selector:
    matchLabels:
      {{- include "application-base.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: {{ .Values.workload.stateful.updateStrategy.type }}
    {{- if and (eq .Values.workload.stateful.updateStrategy.type "RollingUpdate") .Values.workload.stateful.updateStrategy.rollingUpdate }}
    rollingUpdate:
      {{- toYaml .Values.workload.stateful.updateStrategy.rollingUpdate | nindent 6 }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "application-base.selectorLabels" . | nindent 8 }}
        {{- with .Values.workload.podLabels }}
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
        {{- end }}
      {{- $annotations := merge (.Values.workload.podAnnotations | default dict) (.Values.commonAnnotations | default dict) }}
      {{- with $annotations }}
      annotations:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
    spec:
      {{- include "application-base.podSpec" . | nindent 6 }}
  {{- with .Values.workload.stateful.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
{{- end }}
