{{- if and .Values.workload.enabled (eq .Values.workload.type "stateful") }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "application-base.fullname" . }}
  labels:
    {{- include "application-base.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.workload.autoscaling.enabled }}
  replicas: {{ .Values.workload.replicas }}
  {{- end }}
  serviceName: {{ ternary (printf "%s-headless" (include "application-base.fullname" .)) (include "application-base.fullname" .) .Values.network.headlessService.enabled }}
  podManagementPolicy: {{ .Values.workload.stateful.podManagementPolicy }}
  selector:
    matchLabels:
      {{- include "application-base.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: {{ .Values.workload.stateful.updateStrategy.type }}
    {{- if and (eq .Values.workload.stateful.updateStrategy.type "RollingUpdate") .Values.workload.stateful.updateStrategy.rollingUpdate }}
    rollingUpdate:
      {{- toYaml .Values.workload.stateful.updateStrategy.rollingUpdate | nindent 6 }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "application-base.selectorLabels" . | nindent 8 }}
        {{- with .Values.workload.podLabels }}
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
        {{- end }}
      {{- $annotations := merge (.Values.workload.podAnnotations | default dict) (.Values.commonAnnotations | default dict) }}
      {{- with $annotations }}
      annotations:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "application-base.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.accessControl.serviceAccount.automountServiceAccountToken }}
      {{- with .Values.workload.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- with .Values.workload.podSecurityContext }}
      securityContext:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- with .Values.workload.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- if .Values.workload.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.workload.terminationGracePeriodSeconds }}
      {{- end }}
      {{- with .Values.workload.initContainers }}
      initContainers:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "application-base.name" . }}
          image: {{ include "application-base.image" . | quote }}
          imagePullPolicy: {{ .Values.workload.image.pullPolicy }}
          {{- with .Values.workload.command }}
          command:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.args }}
          args:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.ports }}
          ports:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with include "application-base.containerEnvBlock" . }}{{- . | nindent 10 }}{{- end }}
          {{- with include "application-base.containerEnvFromBlock" . }}{{- . | nindent 10 }}{{- end }}
          {{- with .Values.workload.resources }}
          resources:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.securityContext }}
          securityContext:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.readinessProbe }}
          readinessProbe:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.livenessProbe }}
          livenessProbe:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.startupProbe }}
          startupProbe:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.lifecycle }}
          lifecycle:
            {{- toYaml . | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with include "application-base.containerVolumeMountsBlock" . }}{{- . | nindent 10 }}{{- end }}
        {{- with .Values.workload.extraContainers }}
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
        {{- end }}
      {{- with include "application-base.podVolumesBlock" . }}{{- . | nindent 6 }}{{- end }}
      {{- with .Values.workload.nodeSelector }}
      nodeSelector:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- with .Values.workload.affinity }}
      affinity:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- with .Values.workload.tolerations }}
      tolerations:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- with .Values.workload.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
  {{- with .Values.workload.stateful.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
{{- end }}
