eksCluster:
  name: lomeone-eks
nodePool:
  name: default
  labels: {}
  expireAfter: 720h
  terminationGracePeriod: 10m
  requirements:
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: ["t"]
    - key: karpenter.k8s.aws/instance-generation
      operator: In
      values: ["4"]
    - key: karpenter.k8s.aws/instance-hypervisor
      operator: In
      values: ["nitro"]
    - key: karpenter.k8s.aws/instance-cpu
      operator: In
      values: ["1", "2"]
    - key: karpenter.k8s.aws/instance-memory
      operator: In
      values: ["1024", "2048", "4096", "8192"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: kubernetes.io/arch
      operator: In
      values: ["arm64"]
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 10m
  limit:
    cpu: 10
    memory: 40Gi
nodeClass:
  name: default
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@latest
