{{- if .Values.istio.ingress.enabled -}}
{{- $fullName := include "grafana.fullname" . -}}
{{- $namespace := include "grafana.namespace" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: "{{ $fullName }}-gw"
  {{- with .Values.istio.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    istio: {{ .Values.istio.ingress.selector }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: "{{ $fullName }}-vs"
spec:
  hosts:
    - "*"
  gateways:
    - "{{ $fullName }}-gw"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: "{{ $fullName }}.{{ $namespace }}.svc.cluster.local"
            port:
              number: {{ $servicePort }}
{{- end }}