apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: kubecost
spec:
  template:
    metadata:
    sped:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      expireAfter: 720h
      terminationGracePeriod: 10m
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - t
        - key: karpenter.k8s.aws/instance-generation
          operator: In
          values:
            - "4"
        - key: karpenter.k8s.aws/instance-hypervisor
          operator: In
          values:
            - nitro
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values:
            - "1"
            - "2"
        - key: karpenter.k8s.aws/instance-memory
          operator: In
          values:
            - "1024"
            - "2048"
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["ap-northeast-2a"]
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 10m
  limit:
    cpu: 4
    memory: 4Gi
