{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: istiod{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: istiod
    istio.io/rev: {{ .Values.revision | default "default" | quote }}
    install.operator.istio.io/owning-resource: {{ .Values.ownerName | default "unknown" }}
    operator.istio.io/component: "Pilot"
    release: {{ .Release.Name }}
    istio: pilot
spec:
{{/*my custom filed*/}}
  {{- if .Values.global.defaultPodDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.global.defaultPodDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.global.defaultPodDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.global.defaultPodDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app: istiod
      {{- if ne .Values.revision "" }}
      istio.io/rev: {{ .Values.revision | quote }}
      {{- else }}
      istio: pilot
      {{- end }}
---
{{- end }}
