{{- if .Values.ingress.enabled -}}
{{- $fullName := include "argo-cd.fullname" . -}}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: "{{ $fullName }}-gw"
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    istio: "ingress"
  servers:
    - hosts:
      - {{ .Values.ingress.hosts.host }}
      port:
        number: 80
        name: http
        protocol: HTTP2

{{- end }}
