{{- $fullName := include "argo-cd.fullname" . -}}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: "{{ $fullName }}-vs"
spec:
  hosts:
    - {{ .Values.ingress.hosts.host }}
  gateways:
    - "{{ $fullName }}-gw"
  http:
    - name: argo-cd
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: argocd-server.argo.svc.cluster.local
            port:
              number: 80
