config:
  argocd:
    serverAddress: https://argocd-server

  registries:
    - name: Docker Hub
      api_url: https://registry-1.docker.io

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 32Mi
