image:
  registry: 396428372646.dkr.ecr.ap-northeast-2.amazonaws.com/docker-hub

metrics:
  enabled: true
  podAnnotations:
    prometheus.io/port: "7979"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
