serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::396428372646:role/KarpenterControllerRole-lomeone-eks

replicas: 1

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: karpenter.sh/nodepool
              operator: DoesNotExist
            - key: eks.amazonaws.com/nodegroup
              operator: In
              values: ["default_node_group"]

controller:
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      memory: 512Mi

settings:
  clusterName: lomeone-eks
  interruptionQueue: Karpenter-lomeone-eks-SpotInterruptionQueue
